services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"  # Expose PostgreSQL port

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"  # Expose Adminer on a different port
